version: '3.1'
services:
  quorum-device:
    build: .
    container_name: quorum-device
    restart: on-failure
    volumes:
    - /mnt/mpool/docker-volumes/corosync-data:/etc/corosync
    networks:
      iot:
         ipv4_address: 10.0.10.6

networks:
  iot:
    external: true
